spring:
  application:
    name: spring-6-gateway
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://rest-mvc:8080
          enabled: true
          predicates:
            - Path=/api/v1/**
        - id: spring-6-reactive
          uri: http://reactive:8080
          enabled: true
          predicates:
            - Path=/api/v2/*
        - id: spring-6-reactive-mongo
          uri: http://reactive-mongo:8080
          enabled: true
          predicates:
            - Path=/api/v3/*
        - id: spring-6-auth-server
          uri: http://auth-server:9000
          enabled: true
          predicates:
            - Path=/oauth2/**
          
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      # Exclude HTML-related calls and specific endpoints that Logbook doesn't handle correctly
      - path: /actuator/health/**

      - path: /**/h2-console/**  # Exclude H2 console
      - path: /**/swagger-ui/**  # Exclude Swagger UI if used
      - path: /**/v3/api-docs/** # Exclude OpenAPI docs if used

      # Exclude HTML-related calls and web resources
      - path: /**/*.html
      - path: /**/*.css
      - path: /**/*.js
      - path: /**/*.png
      - path: /**/*.jpg
      - path: /**/*.jpeg
      - path: /**/*.gif
      - path: /**/*.ico
      - path: /**/favicon.ico
      - path: /**/webjars/**
      # Exclude other common web resources
      - path: /**/assets/**
      - path: /**/static/**
      - path: /**/public/**
      - path: /**/resources/**
      # Add more exclusions as needed

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  show-actuator: true
  show-oauth2-endpoints: true
  api-docs:
    enabled: true
  swagger-ui:
    oauth:
      # do that not on production!
      client-id: messaging-client
      client-secret: secret
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: spring-6-rest-mvc
        url: /api/v1/v3/api-docs
      - name: spring-6-reactive
        url: /api/v2/v3/api-docs
      - name: spring-6-reactive-mongo
        url: /api/v3/v3/api-docs
      - name: spring-6-data-rest
        url: /api/v4/v3/api-docs
      - name: spring-6-auth-server
        url: /oauth2/v3/api-docs
