apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - image: spring-6-auth-server:0.0.1-SNAPSHOT
        name: spring-6-auth-server
        resources: {}
        env:
          - name: MYSQL_USER
            value: restadmin
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: restdb
          - name: MYSQL_ROOT_PASSWORD
            value: password
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 9000
          failureThreshold: 30
          periodSeconds: 10    
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
