apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: auth-server
  type: ClusterIP

