apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive
  name: reactive
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reactive
  type: ClusterIP

