apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-mvc
  type: ClusterIP

