apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:9
        name: mysql
        resources: {}
        env:
          - name: MYSQL_USER
            value: restadmin
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: restmvcdb  
          - name: MYSQL_ROOT_PASSWORD
            value: password
        readinessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - -h
              - localhost
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1 
        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - -h
              - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3  

