apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive-mongo
  name: reactive-mongo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reactive-mongo
  type: ClusterIP

