### this retrieves the bearer token. use the token in the request below
POST http://localhost:{{auth-server-port}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

### this retrieves the bearer token. use the token in the request below
POST http://host.docker.internal:{{auth-server-port}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

### this retrieves the bearer token. use the token in the request below. When running via gateway we need to retrieve the token via gateway!
POST http://localhost:{{gateway-port}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

### this retrieves the bearer token. use the token in the request below. When running via gateway we need to retrieve the token via gateway!
POST http://host.docker.internal:{{auth-server-port}}/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=message.read message.write

###
GET http://localhost:{{gateway-port}}/.well-known/openid-configuration
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:{{gateway-port}}//.well-known/oauth-authorization-server
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

### ist zurzeit nicht aufgesetzt in auth server
GET http://localhost:{{auth-server-port}}/userinfo
Accept: application/json
Authorization: Bearer {{$auth.token("open-id")}}

### ist zurzeit nicht aufgesetzt in auth server
GET http://localhost:{{gateway-port}}/userinfo
Accept: application/json
Authorization: Bearer {{$auth.token("open-id")}}

### actuator
GET http://localhost:{{auth-server-port}}/actuator/info
Accept: application/json

### actuator via gateway
GET http://localhost:{{gateway-port}}/oauth2/actuator/info
Accept: application/json



