# First you need to retrieve a valid token with the auth server request
### spring-6-rest-mvc
GET http://localhost:8080/api/v1/beer/listBeers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJlMzQyZDZmZS03ZTdlLTRjNTYtODFjYy01OTk5OWJlODdhNWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMzkzMTQyNiwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2ZXI6OTAwMCIsImV4cCI6MTczMzkzMTcyNiwiaWF0IjoxNzMzOTMxNDI2LCJqdGkiOiI0MmZjYzRmNC1jZWFiLTRkN2QtOWY3Yy0yMWMwOWE3MTQxNTYifQ.auek9EhA_5NxqmkvZv5xR6EbKG7pSNb3bX8Z9DDVFUVvIOyIGC4snuscidjA3NvmOVGnZSb4V4O188m0JibJhjoVaUAs5510r4kuo8SpTM96_TLs8t9zkSJfWNuQ1wxDLUTnHwAxpdjSY-5U2gZPLHFpVOLrAhvMM4rXvNFMjZQwB4M8K3dh7PDKI2vRwS9QW--gCCTELwbMo04Y444HO8aXs_3QWjl7l5W1k_0lxh-SEPppo8AFaUFUqvZmO2HHDMvHyY2Zxwfu9-_bZid-YECQ4hW6jHNMqEESUVxOA9zouFIB6r8Wij73SOY1gEXca6uhfI0-7L0TBvmjtAnDvA

### spring-6-reactive
GET http://localhost:8080/api/v2/beer
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJlMzQyZDZmZS03ZTdlLTRjNTYtODFjYy01OTk5OWJlODdhNWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMzkzMTQyNiwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2ZXI6OTAwMCIsImV4cCI6MTczMzkzMTcyNiwiaWF0IjoxNzMzOTMxNDI2LCJqdGkiOiI0MmZjYzRmNC1jZWFiLTRkN2QtOWY3Yy0yMWMwOWE3MTQxNTYifQ.auek9EhA_5NxqmkvZv5xR6EbKG7pSNb3bX8Z9DDVFUVvIOyIGC4snuscidjA3NvmOVGnZSb4V4O188m0JibJhjoVaUAs5510r4kuo8SpTM96_TLs8t9zkSJfWNuQ1wxDLUTnHwAxpdjSY-5U2gZPLHFpVOLrAhvMM4rXvNFMjZQwB4M8K3dh7PDKI2vRwS9QW--gCCTELwbMo04Y444HO8aXs_3QWjl7l5W1k_0lxh-SEPppo8AFaUFUqvZmO2HHDMvHyY2Zxwfu9-_bZid-YECQ4hW6jHNMqEESUVxOA9zouFIB6r8Wij73SOY1gEXca6uhfI0-7L0TBvmjtAnDvA

### spring-6-reactive-mongo
GET http://localhost:8080/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJlMzQyZDZmZS03ZTdlLTRjNTYtODFjYy01OTk5OWJlODdhNWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMzkzMTQyNiwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vYXV0aC1zZXJ2ZXI6OTAwMCIsImV4cCI6MTczMzkzMTcyNiwiaWF0IjoxNzMzOTMxNDI2LCJqdGkiOiI0MmZjYzRmNC1jZWFiLTRkN2QtOWY3Yy0yMWMwOWE3MTQxNTYifQ.auek9EhA_5NxqmkvZv5xR6EbKG7pSNb3bX8Z9DDVFUVvIOyIGC4snuscidjA3NvmOVGnZSb4V4O188m0JibJhjoVaUAs5510r4kuo8SpTM96_TLs8t9zkSJfWNuQ1wxDLUTnHwAxpdjSY-5U2gZPLHFpVOLrAhvMM4rXvNFMjZQwB4M8K3dh7PDKI2vRwS9QW--gCCTELwbMo04Y444HO8aXs_3QWjl7l5W1k_0lxh-SEPppo8AFaUFUqvZmO2HHDMvHyY2Zxwfu9-_bZid-YECQ4hW6jHNMqEESUVxOA9zouFIB6r8Wij73SOY1gEXca6uhfI0-7L0TBvmjtAnDvA

