# First you need to retrieve a valid token with the auth server request
### spring-6-rest-mvc
GET http://localhost:8080/api/v1/beer/listBeers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJjMDE3MDhmNC03MzhlLTRlYTctOTI3NS0zMTA5ZTBhMzZiYWIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNzg5Mzc4MCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6OTAwMCIsImV4cCI6MTczNzg5NDM4MCwiaWF0IjoxNzM3ODkzNzgwLCJqdGkiOiI2M2FhM2ZhNy00ZWExLTQ2ZDItOWUwYy1hMzIzODkyMWI2Y2UifQ.ZaczI5BnXmaSsbL_LKxmkE7MtFGB4nPu-FlKAras852X83UYkf6eBZ6xlw0RfHeZiFqi5nwUOj4y1JmFpizB-36ln_c8oeBQnpBLMSFflrKK0uKBk0_L2QYfccdUXLX3Q1796GmUlu6FxmAHKNa1AlyTl3M4BS5RqCpjFNOLO_4EexhhnbCVYtZJ4tHTVfrTR0ptwRvp_8O0XWfpgGTIAQ3_ajzjCqrxJBlZzZIAraVk96NvQ8dlHZZl-oT-YLeBf0H6wytsE-jD9Nq7pL8jx-I6IuTsnhRXJaqCHwbz8LQ6j98p45aHnXPzN5ITY2uP79LraNXGfUviGkdMoeUzoQ

### spring-6-reactive
GET http://localhost:8080/api/v2/beer
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJjMDE3MDhmNC03MzhlLTRlYTctOTI3NS0zMTA5ZTBhMzZiYWIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNzg5MzY1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6OTAwMCIsImV4cCI6MTczNzg5NDI1NCwiaWF0IjoxNzM3ODkzNjU0LCJqdGkiOiI0NDhjZjE4MC02NTAyLTQ5NGMtYjNkYi05ZmVhYTJlNTA4NWIifQ.GStfWqPpmZhOhuKK-WD8LGLcS6wOeAZzvYR-ogyQ09z3QxPQrP59yMKAdqo7WQ48Num3aBv5CtKFTeNks3USTuib7teBZRd1XXUpCbDdE5Gs-zUpMNFJTXSl1KGyUIIPUmBRaqMDFRpNdSmmPkmAgwSz7Nb-GFxb5W-Kc_Ny_A8pYcvMZIepk5UX9Rj3tIlHxzd7CdHUpDma0ewDEmzp3khbQ3ZZHIIjN5s8Yvv5y7pTzd_dHnHFJvfkXvcc3zzHa1beUZ4POQX9poSLzoSyED7WOv7SAHbhnNZlA5jtESZrcj6B-nIMjqgtEdUZfe7lvYn-DN7uSR-6UnneV7ocAA

### spring-6-reactive-mongo
GET http://localhost:8080/api/v3/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiJjMDE3MDhmNC03MzhlLTRlYTctOTI3NS0zMTA5ZTBhMzZiYWIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNzg5MzY1NCwic2NvcGUiOlsibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOi8vaG9zdC5kb2NrZXIuaW50ZXJuYWw6OTAwMCIsImV4cCI6MTczNzg5NDI1NCwiaWF0IjoxNzM3ODkzNjU0LCJqdGkiOiI0NDhjZjE4MC02NTAyLTQ5NGMtYjNkYi05ZmVhYTJlNTA4NWIifQ.GStfWqPpmZhOhuKK-WD8LGLcS6wOeAZzvYR-ogyQ09z3QxPQrP59yMKAdqo7WQ48Num3aBv5CtKFTeNks3USTuib7teBZRd1XXUpCbDdE5Gs-zUpMNFJTXSl1KGyUIIPUmBRaqMDFRpNdSmmPkmAgwSz7Nb-GFxb5W-Kc_Ny_A8pYcvMZIepk5UX9Rj3tIlHxzd7CdHUpDma0ewDEmzp3khbQ3ZZHIIjN5s8Yvv5y7pTzd_dHnHFJvfkXvcc3zzHa1beUZ4POQX9poSLzoSyED7WOv7SAHbhnNZlA5jtESZrcj6B-nIMjqgtEdUZfe7lvYn-DN7uSR-6UnneV7ocAA


